AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy StarRocks on Amazon Web Services in a new VPC.'
Metadata:
  LICENSE: Apache License Version 2.0
  QuickStartDocumentation:
    EntrypointName: "Parameters for deploying StatRocsk into an new VPC"
    Order: "1"
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - AvailabilityZones
    - Label:
        default: EC2 configuration
      Parameters:
      - KeyPairName
    - Label:
        default: Environment configuration
      Parameters:
      - LatestAmiId
      - JDKDownLoadURL
      - StarRocksDownLoadURL

    # StarRocks Cluster configuration
    - Label:
        default: StarRocks Cluster configuration
      Parameters:
      - FeNodeCount
      - FeNodeInstanceType
      - BeNodeCount
      - BeNodeInstanceType

    # Fe configuration
    - Label:
        default: Fe configuration
      Parameters:
      - LogDir
      - LogLevel
      - MetaDir

    # BE configuration
    - Label:
        default: BE configuration
      Parameters:
      - SysLogDir
      - SysLogLevel
      - VolumeType
      - VolumeSize
      
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      KeyPairName:
        default: Key pair name
      LatestAmiId:
        default: Reference the latest Amazon Linux AMI in a CloudFormation template
      JDKDownLoadURL:
        default: URL of download JDK 1.8
      StarRocksDownLoadURL:
        default: URL of StarRocks
      FeNodeCount:
        default: Number of StarRocks Fe
      FeNodeInstanceType:
        default: Fe instance type
      BeNodeCount:
        default: Number of StarRocks Be
      BeNodeInstanceType:
        default: Be instance type

      # FE
      LogLevel:
        default: Sys Log Level
      MetaDir:
        default: Meta data dir
      
      # BE
      SysLogLevel:
        default: Sys Log Level
      VolumeType:
        default: Volume type of Be nodes
      VolumeSize:
        default: Volume size of Be nodes
Parameters:
  AvailabilityZones:
    Description: List of Availability Zones (AZs) to use for the VPC subnets. More AZs improve the availability of the system, and fewer AZs reduce the cost of data traffic between AZs).Please select two or more
    Type: List<AWS::EC2::AvailabilityZone::Name>
  KeyPairName: 
    Type: AWS::EC2::KeyPair::KeyName
    Description: Public/private key pairs allow you to securely connect to your instance after it launches.
    Default: CFT-Test
  LatestAmiId:
    Description: Reference the latest Amazon Linux AMI in a CloudFormation template.
    Type: AWS::EC2::Image::Id
#Default: ami-0d648a61f4ab8d0e2
    Default: ami-0cff7528ff583bf9a
  JDKDownLoadURL:
    Description: URL of download JDK 1.8
    Type: String
    Default: https://cdn-thirdparty.starrocks.com/java-se-8u41-ri.tar.gz
  StarRocksDownLoadURL:
    Description: URL of StarRocks
    Type: String
#Default: https://www.starrocks.com/zh-CN/download/request-download/12
    Default: https://download.starrocks.com/en-us/download/request-download/31/ 
  FeNodeCount:
    Type: Number
    Default: 1
    Description: Number of StarRocks Fe
    AllowedValues: 
      - 1
      - 3
  FeNodeInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for fe instances.
    Type: String
  BeNodeCount:
    Type: Number
    Default: 3
    Description: Number of StarRocks Be
    AllowedValues: 
      - 3
      - 4
      - 5
      - 6
  BeNodeInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for be instances.
    Type: String

  # Fe
  LogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    Default: INFO
    AllowedValues: 
      - INFO
      - WARN
      - ERROR
      - FATAL
  MetaDir:
    Description: Dir to save mete data, please to fill in the absolute path
    Type: String
    Default: feDefaultMetaPath

  # Be
  SysLogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    Default: INFO
    AllowedValues: 
      - INFO
      - WARN
      - ERROR
      - FATAL
  VolumeType: 
    Type: String
    Description: EBS volume type (data) to be attached to node in GBs [gp2,gp3,st1], one volume for data storage is mounted automatically by CloudFormation stack.
    Default: gp2
    AllowedValues:
      - gp2
      - gp3
      - st1
      - io1
  VolumeSize: 
    Type: String
    Description: EBS volume size (data) to be attached to node in GBs.
    Default: 50
Conditions:
  4BeNodesCondition: !Or  
    - !Equals [!Ref 'BeNodeCount', '4']
    - !Equals [!Ref 'BeNodeCount', '5']
    - !Equals [!Ref 'BeNodeCount', '6']
  5BeNodesCondition: !Or 
    - !Equals [!Ref 'BeNodeCount', '5'] 
    - !Equals [!Ref 'BeNodeCount', '6']
  6BeNodesCondition: !Equals [!Ref 'BeNodeCount', '6']
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1euv6e68138u2-us-east-1.s3.amazonaws.com/templates/aws-vpc.template.yaml
      Parameters:
        AvailabilityZones:
          !Join
          - ','
          - !Ref AvailabilityZones
        NumberOfAZs: '2'
        CreateNATGateways: 'true'
        PrivateSubnet1ACIDR: 10.0.128.0/20
        PrivateSubnet2ACIDR: 10.0.144.0/20
        PublicSubnet1CIDR: 10.0.160.0/20
        PublicSubnet2CIDR: 10.0.176.0/20
        VPCCIDR: 10.0.0.0/16
        CreateAdditionalPrivateSubnets: 'false'
        CreatePublicSubnets: 'true'
        CreatePrivateSubnets: 'true'
        CreateVPCFlowLogsToCloudWatch: 'false'
        PrivateSubnet1BCIDR: 10.0.192.0/21
        PrivateSubnet2BCIDR: 10.0.200.0/21
        PrivateSubnet3ACIDR: 10.0.64.0/19
        PrivateSubnet3BCIDR: 10.0.208.0/21
        PrivateSubnet4ACIDR: 10.0.96.0/19
        PrivateSubnet4BCIDR: 10.0.216.0/21
        PrivateSubnetATag1: Network=Private
        PrivateSubnetATag2: ''
        PrivateSubnetATag3: ''
        PrivateSubnetBTag1: Network=Private
        PrivateSubnetBTag2: ''
        PrivateSubnetBTag3: ''
        PublicSubnet3CIDR: 10.0.160.0/20
        PublicSubnet4CIDR: 10.0.176.0/20
        PublicSubnetTag1: Network=Public
        PublicSubnetTag2: ''
        PublicSubnetTag3: ''
        VPCFlowLogsCloudWatchKMSKey: ''
        VPCFlowLogsLogGroupRetention: 14
        VPCFlowLogsMaxAggregationInterval: 600
        VPCFlowLogsTrafficType: REJECT
        VPCTenancy: default
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1euv6e68138u2-us-east-1.s3.amazonaws.com/templates/starrocks_bastion.template.yaml
      Parameters:
        KeyPairName: !Ref KeyPairName
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        LatestAmiId: !Ref LatestAmiId
        RemoteAccessCIDR: 0.0.0.0/0
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1euv6e68138u2-us-east-1.s3.amazonaws.com/templates/starrocks_securitygroups.template.yaml
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        VPCCIDR: !GetAtt VPCStack.Outputs.VPCCIDR
        BastionSecurityGroupID: !GetAtt BastionStack.Outputs.BastionSecurityGroupID
  BeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1euv6e68138u2-us-east-1.s3.amazonaws.com/templates/starrocks_be.template.yaml
      Parameters:
        BeNodeCount: !Ref BeNodeCount
        PrivateSubnetID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        StarRocksServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.StarRocksServerSecurityGroup
        KeyPairName: !Ref KeyPairName
        LatestAmiId: !Ref LatestAmiId
        JDKDownLoadURL: !Ref JDKDownLoadURL
        StarRocksDownLoadURL: !Ref StarRocksDownLoadURL
        BeNodeInstanceType: !Ref BeNodeInstanceType
        SysLogDir: beDefaultLogPath
        SysLogLevel: !Ref SysLogLevel
        VolumeType: !Ref VolumeType
        VolumeSize: !Ref VolumeSize
  FeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1euv6e68138u2-us-east-1.s3.amazonaws.com/templates/starrocks_fe.template.yaml
      Parameters:
        PrivateSubnetID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        StarRocksServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.StarRocksServerSecurityGroup
        KeyPairName: !Ref KeyPairName
        LatestAmiId: !Ref LatestAmiId
        JDKDownLoadURL: !Ref JDKDownLoadURL
        StarRocksDownLoadURL: !Ref StarRocksDownLoadURL
        FeNodeInstanceType: !Ref FeNodeInstanceType
        FeNodeCount: !Ref FeNodeCount
        LogDir: feDefaultLogPath
        SysLogLevel: !Ref LogLevel
        MetaDir: !Ref MetaDir
        VolumeType: !Ref VolumeType
        BeInstancePrivateIp1: !GetAtt BeStack.Outputs.BeInstancePrivateIp1
        BeInstancePrivateIp2: !GetAtt BeStack.Outputs.BeInstancePrivateIp2
        BeInstancePrivateIp3: !GetAtt BeStack.Outputs.BeInstancePrivateIp3
        BeInstancePrivateIp4: !If
          - 4BeNodesCondition
          - !GetAtt BeStack.Outputs.BeInstancePrivateIp4
          - 0.0.0.0
        BeInstancePrivateIp5: !If
          - 5BeNodesCondition
          - !GetAtt BeStack.Outputs.BeInstancePrivateIp5
          - 0.0.0.0
        BeInstancePrivateIp6: !If
          - 6BeNodesCondition
          - !GetAtt BeStack.Outputs.BeInstancePrivateIp6
          - 0.0.0.0
